language: java
jdk: openjdk11

script:
   - mvn clean package -DskipTests
   - docker build . --tag $ACR_SERVER/$APP_NAME --tag master
   - docker login -u $ACR_USER -p "$ACR_PASSWORD" $ACR_SERVER
   - docker push $ACR_SERVER/$APP_NAME